pipeline {
    agent any
    
    environment {
            DOCKER_IMAGE_NAME = 'primary_container'
            DOCKER_IMAGE_NAME_SECONDARY = 'secondary_container'
            DOCKERFILE_PATH = 'codefiles/src/Dockerfile.primary'
            DOCKERFILE_PATH_SECONDARY = 'codefiles/src/Dockerfile.secondary'
    }
    
    triggers {
        pollSCM('H/5 * * * *') // Poll every five minutes as an example
    }
    
    stages {
    
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Prepare') {
            steps {
                script {
                    // Retrieve and set the Docker registry URL from Jenkins credentials
                    withCredentials([string(credentialsId: 'dockerRegistryUrl', variable: 'REGISTRY_URL')]) {
                        env.DOCKER_REGISTRY_URL = "${REGISTRY_URL}"
                    }
                }
            }
        }
        stage('Build Docker Images') {
            steps {
                script {
                    parallel (
                        'Build Primary Docker Image': {
                            def dockerRegistryUrl = env.DOCKER_REGISTRY_URL
                            docker.withRegistry(dockerRegistryUrl, 'myACRCredentials') {
                                docker.build(env.DOCKER_IMAGE_NAME, "-f ${env.DOCKERFILE_PATH} codefiles/src/")
                            }
                        },
                        'Build Secondary Docker Image': {
                            def dockerRegistryUrl = env.DOCKER_REGISTRY_URL
                            docker.withRegistry(dockerRegistryUrl, 'myACRCredentials') {
                                docker.build(env.DOCKER_IMAGE_NAME_SECONDARY, "-f ${env.DOCKERFILE_PATH_SECONDARY} codefiles/src/")
                            }
                        }
                    )
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    // Retrieve Docker registry URL from Jenkins secret text
                    def dockerRegistryUrl = env.DOCKER_REGISTRY_URL
                    docker.withRegistry(dockerRegistryUrl, 'myACRCredentials') {
                    // Push Docker image to registry
                    docker.image(DOCKER_IMAGE_NAME).push('latest')
                    }
                }
            }
        }
        
        stage('Build') {
            steps {
                sh 'echo clean'
            }
        }
        
        stage('Test') {
            steps {
                sh 'echo test'
            }
        }
        
        // Add more stages as needed
    }
    
    post {
        success {
            echo 'Build successful'
        }
        failure {
            echo 'Build failed'
        }
    }
}
