apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary_container
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: container-pair-test
    spec:
      containers:
        - image: azacrkub.azurecr.io/primary_container:latest
        name: primary_container
        ports:
        - containerPort: 12345

