apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-container
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: primary-container
  template:
    metadata:
      labels:
        app: primary-container
    spec:
      containers:
        - image: azacrkub.azurecr.io/primary_container:latest
          name: primary-container
          ports:
          - containerPort: 12345

